### ISSUE TITLE
Create a catchy footer

### ISSUE THREAD

**Issue by rajmunkhan** [rajmunkhan/basic-portfolio-template#1]
### Issue: 
Right now the site doesn't have a footer. Requesting a contributor to add one catchy footer. 

### Acceptance criteria:

- [ ] make the footer after the skills section(at the end)
- [ ] give enough padding
- [ ] add social media icons(in the middle of the footer)

**Comment by Alam9835** [comment]
i want to work on this issue

**Comment by taslimmuhammed** [comment]
Ya I will do it , please assign me...
