### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by everly-gif** [rajmunkhan/basic-portfolio-template#4]
### Issue :  

The CONTRIBUTING.md File has not mentioned about **creating a new branch** for development by contributors. Someone needs to add that part to the file as **it's considered a best practice of open source**.

**Comment by rajmunkhan** [comment]
yes @Sajal193 , do u want to work on this issue?

**Comment by rajmunkhan** [comment]
go for it @Sajal193 , I assigned it to u
