### ISSUE TITLE
Add few things in Education Section

### ISSUE THREAD

**Issue by rajmunkhan** [rajmunkhan/basic-portfolio-template#45]
### Edit education section according to the picture

Remove the paragraph and add institution name, duration, and location details according to the pic attached below
![Institute Name xyz gfh asg Duration 2017-2018 Location road 28,b-colony, sagrpur](https://user-images.githubusercontent.com/83774177/138040736-8ff4edc5-b307-42a3-bbd7-7c5f75d768fa.png)

**Comment by TamannaBhasin27** [comment]
Please assign this to me. I will have a look.
