### ISSUE TITLE
edit "ABOUT ME" section

### ISSUE THREAD

**Issue by rajmunkhan** [rajmunkhan/basic-portfolio-template#49]
### EDIT ABOUT ME SECTION

there is a paragraph box in the about me section. **Add a pic beside the paragraph box** as shown in the attachment below. 

**NOTE:** keep the site responsive, wrap the pic below the paragraph box if the screen shrinks.

**Download the pic from here** (link https://unsplash.com/photos/aVbR17HLZTg)

![about me section](https://user-images.githubusercontent.com/83774177/138065467-7598da38-6a5a-4235-a165-9084af086cf7.png)

**Comment by underscoremissa** [comment]
I would like to do this, can you assign me this issue.
Thankyou.

**Comment by rajmunkhan** [comment]
go for it @underscoremissa , plz do it ASAP
