### ISSUE TITLE
Make the About Me section responsive

### ISSUE THREAD

**Issue by rajmunkhan** [rajmunkhan/basic-portfolio-template#52]

**Comment by Manishgupta200** [comment]
Thanks, I'ii try my best

**Comment by Pranjal7852** [comment]
@rajmunkhan I have made the about me section responsive. Do let me know if it served the purspose.
%nbsp;

#56 

![image](https://user-images.githubusercontent.com/68412756/138085160-fc41deb0-7c7d-45af-b60b-fd647eb5b535.png)

**Comment by Manishgupta200** [comment]
It's Done by me. I created a pull request. Please check it

**Comment by Manishgupta200** [comment]
Now, Please check it ... I solved this issue succesfully
