### ISSUE TITLE
Change aesthetic background

### ISSUE THREAD

**Issue by dikshatakyar** [rajmunkhan/basic-portfolio-template#70]
The Background should look more better with contrast with blue color. I will be be adding orange/light blue in contrast with dark blue. @everly-gif , @rajmunkhan please assign this to me.

**Comment by dikshatakyar** [comment]
sure @rajmunkhan  @everly-gif , pls assign this issue then

**Comment by dikshatakyar** [comment]
![image](https://user-images.githubusercontent.com/75247382/138262787-7a689b00-175a-4d7d-b668-4206700fe665.png)
@rajmunkhan @everly-gif ,please look here, I will be adding an image on the left side (portfolio image), please look into the color first so that I can continue further. Thanks.

**Comment by everly-gif** [comment]
> ok @dikshatakyar listen, we have decided to keep the theme as blue and white only. But want something catchy in the background of the hero section. If you can create any good animation graphics stuff for the background of the hero section instead of image, let me know.

HI @dikshatakyar are you working on this? can I close this issue ? if you are working on this , I can assign it to you as well ! :)

**Comment by dikshatakyar** [comment]
Hey @everly-gif , I couldn't think of any animation graphics here, so you can close this issue.
