### ISSUE TITLE
Add experience section to the portfolio

### ISSUE THREAD

**Issue by everly-gif** [rajmunkhan/basic-portfolio-template#78]
Design and add an experience section to go with the portfolio template.

**Comment by VIKAS0264** [comment]
Can you assign this to me ?

**Comment by AntonKA** [comment]
Can you please assign it to me as well?

**Comment by rajmunkhan** [comment]
@VIKAS0264 would u work on this?

**Comment by VIKAS0264** [comment]
> @VIKAS0264 would u work on this?

Yeah

**Comment by everly-gif** [comment]
Assigned @VIKAS0264
