### ISSUE TITLE
Add Get in touch section

### ISSUE THREAD

**Issue by everly-gif** [rajmunkhan/basic-portfolio-template#79]
Add a section with a form with basic input fields. Make sure the design matches the aesthetic of the website.

**Comment by geetika005** [comment]
I will make the pull request today itself 
Please assign it to me again

**Comment by geetika005** [comment]
My work is almost complete

**Comment by rajmunkhan** [comment]
cool @geetika005 , plz go ahead

**Comment by Satya-Chandana** [comment]
could you assign this to me, I can make it look better .

**Comment by everly-gif** [comment]
hi @Satya-Chandana you can create a new issue with your proposed changes

**Comment by Satya-Chandana** [comment]
Yes sure
