### ISSUE TITLE
update in project section

### ISSUE THREAD

**Issue by devesh2511** [rajmunkhan/basic-portfolio-template#87]
Can I update projects section, to avoid the cards content spilling issue? Also adding carousel effect to it
![WhatsApp Image 2021-10-24 at 6 49 38 PM](https://user-images.githubusercontent.com/76024137/138596056-75e0a491-c1d2-483b-832c-285eba937302.jpeg)

**Comment by everly-gif** [comment]
yes pls, we need someone to fix that, assigning this issue to you

**Comment by devesh2511** [comment]
please merge my pull request #89
